language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
before_install:
  - sudo add-apt-repository ppa:cwchien/gradle -y
  - sudo apt-get update -y
  - sudo apt-get install gradle -y
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script: 
  - nosetests
  - restli -s my_project -g Foo -ns com.example
  - cd my_project
  - gradle build
